version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: kodius
      POSTGRES_PASSWORD: kodius
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bernard.crnkovic@icloud.com
      PGADMIN_DEFAULT_PASSWORD: kodius
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-80}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
